### PR TITLE
fix lint warnings

### PR DESCRIPTION
**Pull request by zaz600**
fix lint and vet warnings except this

`ftp.go:328: AuthTLS passes Lock by value: crypto/tls.Config contains sync.Once contains sync.Mutex`

what does it mean? :)

### CODE REVIEW

**Comment by VincenzoLaSpesa** [comment]
> fix lint and vet warnings except this
> ftp.go:328: AuthTLS passes Lock by value: crypto/tls.Config contains sync.Once contains sync.Mutex
> what does it mean? :)

I have no idea... and I don't get this error neither in "go1.5.1 linux/amd64", nor "go1.4.2 windows/amd64".

**Comment by VincenzoLaSpesa** [comment]
Just added issue tracking to project

**Comment by zaz600** [comment]
passes Lock by value: 
When you pass obj having Lock()  to func by value not by reference inside func you have an copy of obj

**Comment by zaz600** [comment]
http://stackoverflow.com/questions/30139279/golang-concurrent-download-deadlock

> You're making a copy of your WaitGroup; you should be passing download_file a pointer to it. – Tim Cooper May 9 '15 at 11:28

**Pull request merged**
