### PR TITLE
replace status codes with const

### PR DESCRIPTION
**Pull request by zaz600**
I replaced statuses with named constants
what do you think of it?
Has the code more readable now?

Can you run whole test? a can't do that because of bandwith limit :)

### CODE REVIEW

**Comment by VincenzoLaSpesa** [comment]
Good idea, the code is more readable now.
But on ftp.fu-berlin.de:21 walk does not work!
[cleanedLog.log.txt](https://github.com/VincenzoLaSpesa/goftp/files/76749/cleanedLog.log.txt)

**Comment by zaz600** [comment]
@VincenzoLaSpesa 
Testing walk on -> ftp.fu-berlin.de:21
--- FAIL: TestWalk_good (7.76s)
        ftp_test.go:135: Can't walk ftp.fu-berlin.de:21 -> No file found
Testing walk on -> ftp.packardbell.com:21
exit status 2

parseUnixLIST returns No file found
[dbg.txt](https://github.com/VincenzoLaSpesa/goftp/files/76789/dbg.txt)

**Comment by zaz600** [comment]
regexp fail because minus in "FU-Berlin"

**Comment by zaz600** [comment]
i tried to fix it in https://github.com/VincenzoLaSpesa/goftp/pull/4

**Pull request merged**
